version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"


#version: '3.1'
#
#services:
#  db:
#    image: mysql
##    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_USER: root
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_DATABASE: translations
#    ports:
#      - 3306:3306
